# Generated by Django 5.1.7 on 2025-03-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('C_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_NAME', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('E_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('E_SURNAME', models.CharField(max_length=25)),
                ('E_NAME', models.CharField(max_length=25)),
                ('E_LASTNAME', models.CharField(max_length=25)),
                ('E_PHONE', models.CharField(max_length=25)),
                ('E_ADDRESS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('P_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('P_NAME', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('S_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('S_NUMBER', models.IntegerField()),
                ('S_DATE', models.DateField()),
                ('S_AMOUNT', models.IntegerField()),
                ('S_EMPLOYER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='E_POST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.position'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('P_NAME', models.CharField(max_length=25)),
                ('P_AVAILABLE', models.CharField(max_length=25)),
                ('P_COST', models.BigIntegerField()),
                ('P_CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
    ]
